version: "3.7"
services:
  embulk:
    build: .
    volumes:
      - .:/app:cached
      - home:/home/app
      - vendor:/vendor
      - $HOME/.gitconfig:/home/app/.gitconfig:ro
      - $HOME/.ssh:/home/app/.ssh:ro
      - $HOME/.gem:/home/app/.gem
    environment:
      BUNDLE_PATH: /vendor/bundle
    env_file: app.env
volumes:
  home:
  vendor:
