version: "2.4"
services:
  app:
    build: .
    volumes:
      - .:/app:cached
      - home:/home/app
      - vendor:/vendor
      - $HOME/.gitconfig:/home/app/.gitconfig:ro
      - $HOME/.netrc:/home/app/.netrc:ro
      - $HOME/.gem:/home/app/.gem
      - $HOME/.gem/credentials:/home/app/.gem/credentials:ro
    environment:
      BUNDLE_PATH: /vendor/bundle
    env_file: app.env
    mem_limit: 512M
volumes:
  home:
  vendor:
